wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715512477.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
LOG_DIR:
  desc: null
  value: ../logs
dataset:
  desc: null
  value: cub
sz_embedding:
  desc: null
  value: 512
sz_batch:
  desc: null
  value: 16
nb_epochs:
  desc: null
  value: 60
gpu_id:
  desc: null
  value: 0
nb_workers:
  desc: null
  value: 4
model:
  desc: null
  value: resnet50
loss:
  desc: null
  value: Proxy_Anchor
optimizer:
  desc: null
  value: adamw
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0001
lr_decay_step:
  desc: null
  value: 10
lr_decay_gamma:
  desc: null
  value: 0.5
alpha:
  desc: null
  value: 32
mrg:
  desc: null
  value: 0.1
IPC:
  desc: null
  value: null
warm:
  desc: null
  value: 1
bn_freeze:
  desc: null
  value: 1
l2_norm:
  desc: null
  value: 1
remark:
  desc: null
  value: ''
